[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pkg-lib"
version = "0.1.0"
description = "Library 2 with some_function"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]